export type routeNames =
  | '/'
  | '/about'
  | '/auth'
  | '/profile'
  | '/projects'
  | '/quiz'
  | '/quiz/small'
  | '/quiz/big'
  | '/quiz/big/:id'
  | '/exchangeRate'
  | '/admin'
  | '/settings'
  | '/contacts'
  | '/catalog'
  | '/*';
